-- Create a table for keeping the Supabase project active
CREATE TABLE IF NOT EXISTS "public"."keep_alive" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NULL DEFAULT ''::TEXT,
  random UUID NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  CONSTRAINT "keep_alive_pkey" PRIMARY KEY (id)
);

-- Add some initial placeholder data
INSERT INTO "public"."keep_alive" (name)
VALUES 
  ('placeholder'),
  ('initial_setup')
ON CONFLICT DO NOTHING;

-- Add comment to explain the table's purpose
COMMENT ON TABLE "public"."keep_alive" IS 'Table used by the inactive-fix script to prevent Supabase from pausing due to inactivity';